const promotionService = require('../../services/promotion-service')
const { PROMOTION_STEPS, createPromotionShare } = require('../../models/promotion-code')
const { getCurrentSession } = require('../../services/session-service')

Page({
  data: { state: 'loading', stateMessage: '', profile: {}, statistics: {}, steps: PROMOTION_STEPS, saving: false, phoneDialogVisible: true, phoneInput: '', phoneError: '', demoGenerated: false },
  onLoad() { this.loadPromotion() },
  async loadPromotion() { try { this.setData({ state: 'loading', stateMessage: '' }); const code = await promotionService.getPromotionCode(); const [statistics, poster] = await Promise.all([promotionService.getStatistics('30d'), promotionService.getPoster()]); const value = { ...code, ...(poster || {}), id: code.promotionCodeId, name: code.name || getCurrentSession().name || '', roleLabel: '市场拓展人', statusLabel: code.statusLabel || '推广码可用', sourceCity: '北京', qrImage: (poster && (poster.posterUrl || poster.qrImageUrl)) || code.qrImageUrl || '' }; this.setData({ state: 'success', profile: value, statistics: statistics || {} }) } catch (error) { this.setData({ state: error.kind === 'FORBIDDEN' ? 'forbidden' : 'recoverable-error', stateMessage: error.message || '推广码暂不可用' }) } },
  onPhoneInput(event) { this.setData({ phoneInput: event.detail.value, phoneError: '' }) },
  confirmPhone() { const phone = String(this.data.phoneInput || '').trim(); if (!/^1\d{10}$/.test(phone)) { this.setData({ phoneError: '请输入正确的11位手机号' }); return } const profile = { name: getCurrentSession().name || '推广员', roleLabel: '市场拓展人', statusLabel: '演示推广码', sourceCity: '北京', ...this.data.profile, qrImage: '/assets/images/promotion-qr.jpg' }; this.setData({ phoneDialogVisible: false, phoneError: '', demoGenerated: true, state: 'success', profile }); wx.showToast({ title: '演示二维码已生成', icon: 'success' }) },
  closePhoneDialog() { if (getCurrentPages().length > 1) wx.navigateBack({ delta: 1 }); else wx.switchTab({ url: '/pages/profile/index' }) },
  retry() { this.loadPromotion() },
  async refreshPromotionCode() { if (this.data.saving) return; this.setData({ saving: true }); try { await promotionService.refreshPromotionCode(); wx.showToast({ title: '推广码已刷新', icon: 'success' }); await this.loadPromotion() } catch (error) { wx.showToast({ title: error.message || '推广码刷新失败', icon: 'none' }) } finally { this.setData({ saving: false }) } },
  handleBack() { if (getCurrentPages().length > 1) wx.navigateBack({ delta: 1 }); else wx.switchTab({ url: '/pages/profile/index' }) },
  async savePromotionCode() { const url = this.data.profile.qrImage; if (!url) { wx.showToast({ title: '推广二维码暂未生成', icon: 'none' }); return } this.setData({ saving: true }); try { const file = await new Promise((resolve, reject) => wx.downloadFile({ url, success: resolve, fail: reject })); if (file.statusCode !== 200) throw new Error('图片下载失败'); await new Promise((resolve, reject) => wx.saveImageToPhotosAlbum({ filePath: file.tempFilePath, success: resolve, fail: reject })); wx.showToast({ title: '已保存到相册', icon: 'success' }) } catch (error) { const denied = String(error && error.errMsg || '').includes('auth deny'); if (denied) wx.showModal({ title: '需要相册权限', content: '请在设置中允许保存图片到相册后重试', confirmText: '去设置', success: (result) => { if (result.confirm) wx.openSetting({}) } }); else wx.showToast({ title: '保存失败，请重试', icon: 'none' }) } finally { this.setData({ saving: false }) } },
  onShareAppMessage() { return createPromotionShare(this.data.profile) },
  onShareTimeline() { const share = createPromotionShare(this.data.profile); return { title: share.title, query: share.path.split('?')[1] || '', imageUrl: share.imageUrl } }
})
